name: run-test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: jethrodaniel/setup-zig@fix-caching
        with:
          version: 0.11.0
      - run: zig build run